version: '2'

volumes:
  craftcms-data:
  postgresql-data:
  craftcms-logs:

services:
    web:
      image: wyveo/craftcms-docker:latest
      ports:
        - 80:80
      volumes:
        - craftcms-logs:/var/log
        - craftcms-data:/usr/share/nginx
      links:
        - postgres
        - redis
      # env vars are replaced in .env
      environment:
        # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
        LANG: C.UTF-8

        # REDIS is linked
        REDIS_HOST: redis

        # DB is linked
        DB_DRIVER: pgsql
        DB_SERVER: postgres
        DB_DATABASE: craft3
        DB_PASSWORD: secret
        PGPASSWORD: secret
        DB_SCHEMA: public
        DB_PORT: '5432'
        DB_USER: craft3
        LANG: C.UTF-8

    postgres:
      image: postgres:10.6
      environment:
        POSTGRES_USER: craft3
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: craft3
        POSTGRES_INITDB_ARGS: "-E UTF8"
      volumes:
        # Persistent data
        - postgresql-data:/var/lib/postgresql/data

    redis:
      image: redis:4.0.11-alpine
      volumes:
        - /data:/data
