# Instrumentation for a GRANA cms development environment. THIS SHALL NEVER BE USED FOR PRODUCTION.
version: '2'

# Create the following volumes for storage of code + data (including logs) separately from the containers (machine definitions)
volumes:
  # craftcms-data is initialised in docker-sync.yml. This volume must be started first before Docker-compose.
  craftcms-data:
    external: true
  mysql-data:
  craftcms-logs:

services:
    web:
      image: grana/craftcms-docker:latest
      container_name: cms
      ports:
        - 80:80
      volumes:
        - craftcms-logs:/var/log
        - craftcms-data:/usr/share/nginx:nocopy
      links:
        - mysql
        - redis
      # env vars are replaced in .env
      environment:
        # Set locale to UTF-8 (https://oncletom.io/2015/docker-encoding/)
        LANG: C.UTF-8

        # REDIS is linked
        REDIS_HOST: redis
        REDIS_PORT_6379_TCP: tcp://redis:6379

        # CRAFT specific environments
        CRAFT_ENVIRONMENT: "production"
        SECURITY_KEY: "2EALRdRDYmRr5cbAD5wxRVdCeZ4qEHgCCzmZZYdjfuXqmSpXW5tN83byEm3" # The secure key Craft will use for hashing and encrypting data (generate/update using ./craft setup/security-key)

        # DB is linked
        DB_DRIVER: mysql
        DB_SERVER: mysql
        DB_DATABASE: craft3
        DB_PASSWORD: secret
        DB_TABLE_PREFIX: "cr_"
        DB_SCHEMA: public
        DB_PORT: '3306'
        DB_USER: craft3
        LANG: C.UTF-8
      # Changing the command to trigger /start.sh to start nginx, php-fpm and other servers, and then install the dependencies as specified by code.
      command: /start.sh && /usr/local/bin/install_dep.sh

    mysql:
      image: mysql:5.7
      container_name: cms_db
      environment:
        MYSQL_USER: craft3
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: craft3
      volumes:
        # Persistent data
        - mysql-data:/var/lib/mysql

    redis:
      image: redis:4.0.10-alpine
      container_name: cms_redis
      volumes:
        - /tmp/redis:/data